create table universe (
  universe_id bigint generated by default as identity primary key,
  name text not null
);

create table owner (
  owner_id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  address text,
  universe_id bigint not null references universe (universe_id)
);

create table employee (
  employee_id bigint generated by default as identity primary key,
  name text not null,
  job_role text not null,
  specialty text,
  hire_date date not null,
  phone text not null,
  email text not null,
  schedule text
);

create table patient (
  patient_id bigint generated by default as identity primary key,
  dob date,
  name text not null,
  color text,
  owner_id bigint not null references owner (owner_id),
  species_id bigint,
  breed_id bigint,
  universe_id bigint not null references universe (universe_id)
);

create table visit (
  visit_id bigint generated by default as identity primary key,
  patient_id bigint not null references patient (patient_id),
  start_at timestamptz not null,
  end_at timestamptz,
  reason text,
  vet_id bigint references employee (employee_id)
);

create table diagnosis (
  diagnosis_id bigint generated by default as identity primary key,
  name text not null,
  description text,
  code text
);

create table visit_diagnosis (
  visit_diagnosis_id bigint generated by default as identity primary key,
  visit_id bigint not null references visit (visit_id),
  diagnosis_id bigint not null references diagnosis (diagnosis_id),
  employee_id bigint references employee (employee_id),
  recorded_at timestamptz not null,
  unique (visit_id, diagnosis_id, recorded_at)
);

create table procedure_definition (
  procedure_id bigint generated by default as identity primary key,
  name text not null,
  description text,
  standard_cost numeric(10, 2)
);

create table visit_procedure (
  visit_procedure_id bigint generated by default as identity primary key,
  visit_id bigint not null references visit (visit_id),
  procedure_id bigint not null references procedure_definition (procedure_id),
  employee_id bigint references employee (employee_id),
  performed_at timestamptz not null,
  unique (visit_id, procedure_id, performed_at)
);

create table observation (
  observation_id bigint generated by default as identity primary key,
  visit_procedure_id bigint not null references visit_procedure (visit_procedure_id),
  observation_type text,
  observed_value numeric(10, 2),
  unit text,
  description text
);

create table ability (
  ability_id bigint generated by default as identity primary key,
  name text not null,
  ability_type text
);

create table patient_ability (
  patient_ability_id bigint generated by default as identity primary key,
  patient_id bigint not null references patient (patient_id),
  ability_id bigint not null references ability (ability_id),
  unique (patient_id, ability_id)
);

create table invoice (
  invoice_id bigint generated by default as identity primary key,
  visit_id bigint not null references visit (visit_id),
  status text not null,
  due_date date,
  issue_date date not null
);

create table line_item (
  line_item_id bigint generated by default as identity primary key,
  invoice_id bigint not null references invoice (invoice_id),
  line_item_type text not null,
  visit_procedure_id bigint references visit_procedure (visit_procedure_id),
  medication_id bigint,
  vaccination_id bigint,
  boarding_stay_id bigint
);

create table payment (
  payment_id bigint generated by default as identity primary key,
  invoice_id bigint not null references invoice (invoice_id),
  payment_date date not null,
  amount numeric(10, 2) not null,
  payment_method text not null
);
